//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap FANTAS {
            get {
                object obj = ResourceManager.GetObject("FANTAS", resourceCulture);
=======
        internal static System.Drawing.Bitmap esqueletos {
            get {
                object obj = ResourceManager.GetObject("esqueletos", resourceCulture);
>>>>>>> 1fb1bf19a4a1faebc7c23ffa85478a15dd8dcfbb
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap FANTAS1 {
            get {
                object obj = ResourceManager.GetObject("FANTAS1", resourceCulture);
=======
        internal static System.Drawing.Bitmap funcionario {
            get {
                object obj = ResourceManager.GetObject("funcionario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fundocinza {
            get {
                object obj = ResourceManager.GetObject("fundocinza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fundocinzaclaro {
            get {
                object obj = ResourceManager.GetObject("fundocinzaclaro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fundocinzaformat {
            get {
                object obj = ResourceManager.GetObject("fundocinzaformat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giphy {
            get {
                object obj = ResourceManager.GetObject("giphy", resourceCulture);
>>>>>>> 1fb1bf19a4a1faebc7c23ffa85478a15dd8dcfbb
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Homepage {
            get {
                object obj = ResourceManager.GetObject("Homepage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap nn1 {
            get {
                object obj = ResourceManager.GetObject("nn1", resourceCulture);
=======
        internal static System.Drawing.Bitmap logo2 {
            get {
                object obj = ResourceManager.GetObject("logo2", resourceCulture);
>>>>>>> 1fb1bf19a4a1faebc7c23ffa85478a15dd8dcfbb
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tela_Menu1 {
            get {
                object obj = ResourceManager.GetObject("Tela Menu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tela_Menu11 {
            get {
                object obj = ResourceManager.GetObject("Tela Menu11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tela_Menu12 {
            get {
                object obj = ResourceManager.GetObject("Tela Menu12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tela_Menu13 {
            get {
                object obj = ResourceManager.GetObject("Tela Menu13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TelaGerente {
            get {
                object obj = ResourceManager.GetObject("TelaGerente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TelaGerenteEstoque {
            get {
                object obj = ResourceManager.GetObject("TelaGerenteEstoque", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap TelaLogado {
            get {
                object obj = ResourceManager.GetObject("TelaLogado", resourceCulture);
=======
        internal static System.Drawing.Bitmap titulo {
            get {
                object obj = ResourceManager.GetObject("titulo", resourceCulture);
>>>>>>> 1fb1bf19a4a1faebc7c23ffa85478a15dd8dcfbb
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap TelaPerfilUser {
            get {
                object obj = ResourceManager.GetObject("TelaPerfilUser", resourceCulture);
=======
        internal static System.Drawing.Bitmap titulo1 {
            get {
                object obj = ResourceManager.GetObject("titulo1", resourceCulture);
>>>>>>> 1fb1bf19a4a1faebc7c23ffa85478a15dd8dcfbb
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap TelaPerfilUser__1_ {
            get {
                object obj = ResourceManager.GetObject("TelaPerfilUser (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TelaPerfilUser__1_1 {
            get {
                object obj = ResourceManager.GetObject("TelaPerfilUser (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TelaPerfilUser__1_2 {
            get {
                object obj = ResourceManager.GetObject("TelaPerfilUser (1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TelaPerfilUser1 {
            get {
                object obj = ResourceManager.GetObject("TelaPerfilUser1", resourceCulture);
=======
        internal static System.Drawing.Bitmap titulo11 {
            get {
                object obj = ResourceManager.GetObject("titulo11", resourceCulture);
>>>>>>> 1fb1bf19a4a1faebc7c23ffa85478a15dd8dcfbb
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
